### ISSUE TITLE
Cannot using tabs / Segmented control

### ISSUE THREAD

**Issue by chandranoor** [lecoueyl/mijin#27]
**Describe the bug**
Pasted the code from documentation, but doesn't work. Selected item wont change.

If you don't mind, please give an example for tab and segemented control with contents.

**To Reproduce**
1. Go to https://lecoueyl.github.io/mijin.web/docs/atoms/segmentedControl
2. Copy the example code
3. Paste it on nuxt 
4. Element shows up but doesn't work

**Expected behavior**
Some components work like charm ( I tried toast and popover both are working properly)

**Comment by lecoueyl** [comment]
I'm going to close this issue since no response for 14 days.
If you feel this issue should be reopened, create a new issue linking back to this one for added context. Thanks!

**Comment by chandranoor** [comment]
Oh I see, I will look into code used in the documentation for other components

Thanks for your reply, it's really helpful.
